# general settings
# Claculate on 720P
# Params: 0.228M, FLOPs: 51.532G, Activations: 299M
name: train_SAFM_X2_denoise
model_type: SRModel
scale: 2
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 1234

# dataset and data loader settings
datasets:
  train:
    name: DIV2k
    type: PairedImageDataset
    dataroot_gt: datasets/DL2K/HR_mod2_sub #datasets/DL2K/DL2K_train_HR_sub
    dataroot_lq: datasets/DL2K/X2_sub
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 128
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4 #8  # If Broken Pipe (set small, as 4)
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 100 #10
    prefetch_mode: ~

  # we use multiple validation datasets. The SR benchmark datasets can be download from: https://cv.snu.ac.kr/research/EDSR/benchmark.tar
  # val:
  #   name: DIV2K_val100
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/DIV2K/DIV2K_Valid/HR
  #   dataroot_lq: datasets/DIV2K/DIV2K_Valid/LR_bicubic/X2
  #   filename_tmpl: '{}x2'
  #   io_backend:
  #     type: disk
  val:
    name: DIV2k
    type: PairedImageDataset
    dataroot_gt: datasets/testsets/DIV2K/HR_mod2
    dataroot_lq: datasets/testsets/DIV2K/X2
    io_backend:
      type: disk

# network structures
network_g:
  type: SAFMN
  dim: 36
  n_blocks: 8
  ffn_scale: 2.0
  upscaling_factor: 2

# path
path:
  pretrain_network_g: /home/aleks/main/huawei/ISR_Task_2023/pretrain_models/safm/SAFMN_DF2K_x2.pth
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [500000]
    restart_weights: [1]
    eta_min: !!float 1e-5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: true
  pbar: False

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 2
      test_y_channel: False
      better: higher  # the higher, the better. Default: higher
    # ssim:
    #   type: calculate_ssim
    #   crop_border: 2
    #   test_y_channel: False
    #   better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
  use_tb_logger: true
  wandb:
    project: ntire2023
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500