# Parameters for initialization
initialization:
  n_epochs: 15
  val_step: 75
  model_name: "unet_depth_degr"
  seed: 17

# Parameters for datasets and dataloaders
datasets:
  train_datasets:
    image_dir: "/home/arazin/main/work/HUAWEI/ISR/ISR_With_Depth_Estimation/ldm_custom_pipeline/datasets/images/trainset"
    depth_dir: "/home/arazin/main/work/HUAWEI/ISR/ISR_With_Depth_Estimation/ldm_custom_pipeline/datasets/depth_maps/trainset"
    batch_size: 64
    shuffle: true
    transform: "BaseTransform"
    degradation: "BSRDegradation"
    image_dataset: "ImageDataset"
    cond_dataset: "ConditionDataset"
    image_transform_params:
        size: 128
        resize: true
    cond_transform_params:
        size: 32
        resize: true
    degradation_params: {}

  val_datasets:
    image_dir: "/home/arazin/main/work/HUAWEI/ISR/ISR_With_Depth_Estimation/ldm_custom_pipeline/datasets/images/valset"
    depth_dir: "/home/arazin/main/work/HUAWEI/ISR/ISR_With_Depth_Estimation/ldm_custom_pipeline/datasets/depth_maps/valset"
    batch_size: 64
    shuffle: true
    transform: "BaseTransform"
    degradation: "BSRDegradation"
    image_dataset: "ImageDataset"
    cond_dataset: "ConditionDataset"
    image_transform_params:
        size: 128
        resize: true
    cond_transform_params:
        size: 32
        resize: true
    degradation_params: {}

  test_datasets:
    image_dir: "/home/arazin/main/work/HUAWEI/ISR/ISR_With_Depth_Estimation/ldm_custom_pipeline/datasets/images/testset"
    depth_dir: "/home/arazin/main/work/HUAWEI/ISR/ISR_With_Depth_Estimation/ldm_custom_pipeline/datasets/depth_maps/testset"
    batch_size: 4
    shuffle: true
    transform: "BaseTransform"
    degradation: "BSRDegradation"
    image_dataset: "ImageDataset"
    cond_dataset: "ConditionDataset"
    image_transform_params:
        size: 128
        resize: true
    cond_transform_params:
        size: 32
        resize: true
    degradation_params: {}

# Parameters for model and optimizer
model:
  device: 'cpu'
  lr: 0.0003
  lr_scheduler: "CosineAnnealingLR"
  lr_scheduler_start_epoch: 5
  lr_scheduler_params:
    T_max: 10
    eta_min: 0.000001
    last_epoch: -1
    verbose: false
  unet_model_params:
    sample_size: 32
    input_channels: 3
    layers_per_block: 2
    block_out_channels:
      - 32
      - 64
      - 64
    addition_condition: 1
  pretrain_pipeline: "LDMSuperResolutionPipeline"
  pretrain_model_id: "CompVis/ldm-super-resolution-4x-openimages"
  noise_scheduler: "DDIMScheduler"
  scheduler_train_params: 
    num_train_timesteps: 1000
    beta_schedule: "squaredcos_cap_v2"
  scheduler_inference_params:
    num_inference_steps: 100
  loss: "MSE"
  test_metric: "PSNR"

logging:
  project_name: "ldm_conditioned"
  experiment_name: "vqvae-pretrain_conditioned_unet2d-train_exp-0"
  logdir: "/home/arazin/main/work/HUAWEI/ISR/ISR_With_Depth_Estimation/ldm_custom_pipeline/logdir"
  logger: # "wandb" # "mlflow"